# Generated by Django 4.2 on 2025-04-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simfooduser',
            name='role',
            field=models.CharField(choices=[('Headchef', 'headchef'), ('Consumer', 'consumer'), ('Cook', 'cook')], default='Consumer', max_length=8),
        ),
    ]
