# Generated by Django 4.2 on 2025-04-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_simfooduser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='simfooduser',
            name='came_to_eat',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='simfooduser',
            name='role',
            field=models.CharField(choices=[('Monitor', 'monitor'), ('Cook', 'cook'), ('Consumer', 'consumer'), ('Headchef', 'headchef')], default='Consumer', max_length=8),
        ),
    ]
