# Generated by Django 4.2 on 2025-04-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_simfooduser_came_to_eat_alter_simfooduser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simfooduser',
            name='role',
            field=models.CharField(choices=[('headchef', 'Headchef'), ('consumer', 'Consumer'), ('cook', 'Cook'), ('monitor', 'Monitor')], default='Consumer', max_length=8),
        ),
    ]
