# Generated by Django 4.2 on 2025-04-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_simfooduser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simfooduser',
            name='role',
            field=models.CharField(choices=[('cook', 'Cook'), ('headchef', 'Headchef'), ('consumer', 'Consumer'), ('monitor', 'Monitor')], default='Consumer', max_length=8),
        ),
    ]
