# Generated by Django 4.2 on 2025-04-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_simfooduser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simfooduser',
            name='role',
            field=models.CharField(choices=[('consumer', 'Consumer'), ('headchef', 'Headchef'), ('cook', 'Cook'), ('monitor', 'Monitor')], default='Consumer', max_length=8),
        ),
    ]
