# Generated by Django 4.2 on 2025-04-07 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'pending'), ('Completed', 'completed')], default='pending', max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MenuModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('dal', models.CharField(choices=[('Dal Fry', 'dal_fry'), ('Gujarati Dal', 'gujarati_dal'), ('Mix Dal', 'mix_dal'), ('Punjabi Dal', 'punjabi_dal'), ('Khatti Meethi Dal', 'khatti_meethi_dal'), ('Dal Tadka', 'dal_tadka'), ('Kadhi', 'kadhi')], max_length=20)),
                ('rice', models.CharField(choices=[('Plain Rice', 'plain_rice'), ('Jeera Rice', 'jeera_rice'), ('Pulao', 'pulao'), ('Veg Biryani', 'veg_biryani')], max_length=20)),
                ('sabzi', models.CharField(choices=[('Aloo Bhindi', 'aloo_bhindi'), ('Butter Paneer', 'butter_paneer'), ('Gobi Aloo', 'gobi_aloo'), ('Tinda', 'tinda'), ('Lasaniya Aloo', 'lasaniya_aloo'), ('Mix Veg', 'mix_veg'), ('Dahi Aloo', 'dahi_aloo'), ('Rajma', 'rajma'), ('Chole', 'chole'), ('Tuver', 'tuver')], max_length=20)),
                ('roti', models.CharField(choices=[('Plain Roti', 'plain_roti'), ('Bajra Roti', 'bajra_roti'), ('Puri', 'puri'), ('Baati', 'baati'), ('Parantha', 'parantha')], max_length=20)),
                ('extras', multiselectfield.db.fields.MultiSelectField(choices=[('Salad', 'salad'), ('Pickle', 'pickle'), ('Jaggery', 'jaggery'), ('Pappad', 'Pappad'), ('Sandwich Dhokla', 'sandwich_dhokla'), ('Bakharwadi', 'bakharwadi'), ('Fulwadi', 'fulwadi'), ('Patra', 'patra'), ('Bhajiya', 'bhajiya'), ('Khandvi', 'khandvi'), ('Khaman', 'khaman')], max_length=50)),
                ('jain_dal', models.CharField(choices=[('Gujarati Dal', 'gujarati_dal'), ('Mix Dal', 'mix_dal'), ('Khatti Meethi dal', 'khatti_meethi_dal'), ('Kadhi', 'kadhi')], max_length=20)),
                ('jain_sabzi', models.CharField(choices=[('Pappad nu shak', 'pappad_nu_shak'), ('Kela nu shak', 'kela_nu_shak'), ('Kobij', 'kobij'), ('Rajma', 'rajma'), ('Chole', 'chole'), ('Tuver', 'tuver')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_prepared', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
