# Generated by Django 4.2 on 2025-04-08 06:51

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('headchef', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menumodel',
            name='dal',
            field=models.CharField(choices=[('dal_fry', 'Dal Fry'), ('gujarati_dal', 'Gujarati Dal'), ('mix_dal', 'Mix Dal'), ('punjabi_dal', 'Punjabi Dal'), ('khatti_meethi_dal', 'Khatti Meethi Dal'), ('dal_tadka', 'Dal Tadka'), ('kadhi', 'Kadhi')], max_length=20),
        ),
        migrations.AlterField(
            model_name='menumodel',
            name='extras',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('salad', 'Salad'), ('pickle', 'Pickle'), ('jaggery', 'Jaggery'), ('pappad', 'Pappad'), ('sandwich_dhokla', 'Sandwich Dhokla'), ('bakharwadi', 'Bakharwadi'), ('fulwadi', 'Fulwadi'), ('patra', 'Patra'), ('bhajiya', 'Bhajiya'), ('khandvi', 'Khandvi'), ('khaman', 'Khaman'), ('dhokla', 'Dhokla')], max_length=50),
        ),
        migrations.AlterField(
            model_name='menumodel',
            name='jain_dal',
            field=models.CharField(choices=[('gujarati_dal', 'Gujarati Dal'), ('mix_dal', 'Mix Dal'), ('khatti_meethi_dal', 'Khatti Meethi Dal'), ('kadhi', 'Kadhi')], max_length=20),
        ),
        migrations.AlterField(
            model_name='menumodel',
            name='jain_sabzi',
            field=models.CharField(choices=[('pappad_nu_shak', 'Pappad nu shak'), ('kela_nu_shak', 'Kela nu shak'), ('kobij', 'Kobij'), ('rajma', 'Rajma'), ('chole', 'Chole'), ('tuver', 'Tuver')], max_length=20),
        ),
        migrations.AlterField(
            model_name='menumodel',
            name='rice',
            field=models.CharField(choices=[('plain_rice', 'Plain Rice'), ('jeera_rice', 'Jeera Rice'), ('pulao', 'Pulao'), ('veg_biryani', 'Veg Biryani')], max_length=20),
        ),
        migrations.AlterField(
            model_name='menumodel',
            name='roti',
            field=models.CharField(choices=[('plain_roti', 'Plain Roti'), ('bajra_roti', 'Bajra Roti'), ('puri', 'Puri'), ('baati', 'Baati'), ('parantha', 'Parantha')], max_length=20),
        ),
        migrations.AlterField(
            model_name='menumodel',
            name='sabzi',
            field=models.CharField(choices=[('aloo_bhindi', 'Aloo Bhindi'), ('butter_paneer', 'Butter Paneer'), ('gobi_aloo', 'Gobi Aloo'), ('tinda', 'Tinda'), ('lasaniya_aloo', 'Lasaniya Aloo'), ('mix_veg', 'Mix Veg'), ('dahi_aloo', 'Dahi Aloo'), ('rajma', 'Rajma'), ('chole', 'Chole'), ('tuver', 'Tuver')], max_length=20),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=9),
        ),
    ]
