# Generated by Django 4.2 on 2025-04-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headchef', '0002_alter_menumodel_dal_alter_menumodel_extras_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menumodel',
            name='date',
            field=models.DateField(editable=False, unique=True),
        ),
    ]
