# Generated by Django 4.2 on 2025-04-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headchef', '0003_alter_menumodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menumodel',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
