# Generated by Django 4.2 on 2025-04-10 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('headchef', '0004_alter_menumodel_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chose_yes_came', models.IntegerField()),
                ('chose_yes_not_came', models.IntegerField()),
                ('chose_no', models.IntegerField()),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_stats', to='headchef.menumodel')),
            ],
        ),
    ]
